[package]
name = "pontem_adapter_v2"
version = "0.0.0"
authors = []

# 0x58c0d7fff86f80a2c8608abc5445cb7b2a75ffe6ec6714cb01ae96ecf199e25f
[addresses]
pontem_adapter_v2 = "0xf0e565cd2b851573d2f939553c866e9b9b5fc9f14edb6213cbcd623beb22b47c"

[dev-addresses]


[dependencies]
Liquidswapv05 = { local = "../../interface/pontem-Liquidswap-v2" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"



