[package]
name = "dexrouter"
version = "2.0.0"

[addresses]
dexrouter = "0x3faf7a406a14b9cdeb842f9caf23826eb19cc78d11997298b7e0115b193be8a1"
deployer = "0xd2be0d7edad1cb3ecc9bee26bcfc3d595385e9fe309b115ca01e207bc234aefd"

[dependencies]
pontem_adapter =  {local = "./adapters/pontem_adapter"}
pontem_adapter_v2 = {local = "./adapters/pontem_adapter_v2"}
pancake_adapter = {local = "./adapters/pancake_adapter"}
cellana_adapter = {local = "./adapters/cellana_adapter"}
hyperion_adapter = {local = "./adapters/hyperion_adapter"}


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = 'mainnet'

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib/"
rev = 'mainnet'





